# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commonmeta < Formula
  desc ""
  homepage ""
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/front-matter/commonmeta/releases/download/v0.11.0/commonmeta_Darwin_x86_64.tar.gz"
      sha256 "336ab3622c61984476e860034063f481aeddcf7c67dc08ecc7b8794320102e6f"

      def install
        bin.install "commonmeta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/front-matter/commonmeta/releases/download/v0.11.0/commonmeta_Darwin_arm64.tar.gz"
      sha256 "010655627aa46e5ee5955a23c4896748144620fb5cf74d74fb975d9a9b4b4141"

      def install
        bin.install "commonmeta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/commonmeta/releases/download/v0.11.0/commonmeta_Linux_x86_64.tar.gz"
        sha256 "82fe439f4ad39313eec5d0a54430fcf5cb9975026f572b4654c29b6db6e3335a"

        def install
          bin.install "commonmeta"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/front-matter/commonmeta/releases/download/v0.11.0/commonmeta_Linux_arm64.tar.gz"
        sha256 "ece892c8a1f4957c745cd778da049e5f940087ceeee9dd980fbc6c94eff7ee7b"

        def install
          bin.install "commonmeta"
        end
      end
    end
  end
end
